services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\Media\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    OSW3\Media\EventListener\MediaAliasesListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad }